### ISSUE TITLE
【Teensy】フレーム毎にループする仕組みの作成

### ISSUE THREAD

**Issue by nishi10000** [nishi10000/NY_Laser_Project#1]
NY_Laser_Project / Teensy / Teensy_Laser /src/

**Comment by twenty408** [comment]
レビューしました。
全体通して、使わなくなったコードをコメントで残してると読みにくいです。

main_img_fileoutput_canma.py

#19 ～　#22
変数にする意味ある？

#33
height,widthを略してほしくない（何でもかんでも略するとあとで見たときわかんなくなる）

#42
関数名分かりにくいかも。listの長さのこと？

#65
dstって何？

#102
msgに移さなくてもよくない？

#111,112
好みかも知れないけど２行に分けなくてよくない？

#119
jpgファイル取り込みの指定と同じところでファイルパス指定したい

#121
sに入れる必要あるの？

main.cpp

#87,#92
二回開かないといけないの？
void loop()の前にファイル開いたほうがよくない？（ループ時に毎回開きたいの？遅くなりそう）
※聞いたけど書いとくわ

#93,#173～#176
if(!myFile){
  return;
}
にしてコードの深さ下げたらだめ？

#115,#120,#129,#139,#166
全部if分岐の外にやれば１行ですむ。

#105,#107
順を入れ替えたらだめ？変数定義変えなきゃいけないけど、一文字消す処理が消えると思う。

#143
trimする必要あるの？

#150,#153
変数名datacountは分かりにくいと思う。スネークケースでもない。

#164
usec?分かりにくいと思う。wait_timeとかじゃない？
